### ISSUE TITLE
I am getting error "{resizedFile: File, reason: TypeError: Cannot read property 'resizeCanvas' of undefined at http://localhost:4200/vendor.bund…, error: "PICA_ERROR"}"

### ISSUE THREAD

**Issue by lintelbeam** [bergben/ng2-img-tools#17]
when I try to resize the image using this module I am getting error like this.
{resizedFile: File, reason: TypeError: Cannot read property 'resizeCanvas' of undefined at http://localhost:4200/vendor.bund…, error: "PICA_ERROR"}
Anybody can help this problem?
Regards.

**Comment by AnthonyNahas** [comment]
i am facing the same problem

**Comment by bergben** [comment]
Should be fixed now.

**Comment by reactionic127** [comment]
@bergben 
Could you kindly provide a solution how can I fix this issue?
Because I am still facing same problem as before.
Regards.

**Comment by lintelbeam** [comment]
@bergben 
Thanks. It is working fine on my side.
I reinstalled the module and running my app and it is working properly.
Thanks for your help.
Regards.

**Comment by AnthonyNahas** [comment]
i am getting now another error, while the app is being rendered on the server side with nodeJS.
I opened a new issue [here](https://github.com/bergben/ng2-img-tools/issues/19)
